type: adversarial_attack
compatible_adaptation_types: ["frozen"]
base_embeddings_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/embeddings/
attack_batch_size: 8
nb_attack_images: 10000
# ----------------------------------------------------------------------
# PGD attack hyper‑parameters
# ----------------------------------------------------------------------
attack:
  eps:         1.5e-3   # radius of the norm ball (0 → no attack, 1 → full range)
  alpha:       0.001    # step size per PGD iteration (≈ eps / 5)
  n_steps:     5        # number of PGD iterations
  norm:        linf     # { linf | l2 }
  random_start: true    # start from a random point inside the eps‑ball
