type: transformation_invariance
compatible_adaptation_types: ["frozen"]
base_embeddings_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/embeddings/
transformation_invariance_batch_size: 64
nb_images: 1000
